### ISSUE TITLE
Re - Error importing PIL

### ISSUE THREAD

**Issue by the-black-eagle** [daggs1/plugin.audio.100fm-Digital#1]
Hi, I saw your issue at https://github.com/xbmc/xbmc/issues/17522 and have been able to both reproduce it and (I think) fix it.

Have you got more than one version of python3 installed ?  I have 3.6, 3.7 and 3.8.  If I build Kodi and link python3.7 I get the same error as you.  Looking in `/usr/lib/python3/dist-packages/PIL` I see that the shared object files are for python 3.6.  Building Kodi and linking python 3.6 allows the import to work
`-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so`

If that works you will get a new error regarding saving a jpeg as ARGB `bg.save`.  You can fix that by converting the image to RGB first and dropping the alpha channel. Add `bg = bg.convert('RGB')` between `bg.paste` and `bg.save` and it should run again.  It is for me anyway.

**Comment by daggs1** [comment]
Greetings,

thanks for the info, I'll try that.
thing is, I always had multiple python versions, has something got changed in kodi's build env?

**Comment by daggs1** [comment]
your first suggestion worked.
regarding the other error, some of images have transparent bg, afaik, I need the alpha for that, no?

**Comment by the-black-eagle** [comment]
Yes, if they have alpha then you should just save them as PNG files rather than JPEG/JPG.  PNG supports transparency whereas JPG does not.  Kodi will load PNG files just fine.

Ubuntu's repo's supply PIL generally and they, for 18.04 at least, contain 3.6 binaries.  See https://packages.ubuntu.com/bionic/amd64/python3-pil/filelist

**Comment by daggs1** [comment]
> Yes, if they have alpha then you should just save them as PNG files rather than JPEG/JPG. PNG supports transparency whereas JPG does not. Kodi will load PNG files just fine.
> 
> Ubuntu's repo's supply PIL generally and they, for 18.04 at least, contain 3.6 binaries. See https://packages.ubuntu.com/bionic/amd64/python3-pil/filelist

thanks, I'll convert it to png.
if it works I'll update the repo

**Comment by DaVukovic** [comment]
Isn't PIL deprecated anyway?

**Comment by daggs1** [comment]
> Isn't PIL deprecated anyway?
> 
what is the alternative?

> Whatever. I'l close that issue at the Kodi bug tracker. That sounds more like a question which needs to be asked at the forums as I'm not sure where this issue might be related to Kodi.

correct.

closing,

**Comment by DaVukovic** [comment]
2 minutes of google tells me that pillow is the successor

**Comment by DaVukovic** [comment]
Just had an internal talk. You could also try to make a module dependency on `script.module.pil` at your addon.xml

`<import addon="script.module.pil" version="1.1.7"/>` 

the script.module.pil is basically pillow and maybe that will work then

**Comment by daggs1** [comment]
> 2 minutes of google tells me that pillow is the successor
> 
> Buit I'm not a developer. That's just what I found out

I was under the impression what PIL is part of pillow, am I wrong?

> Just had an internal talk. You could also try to make a module dependency on `script.module.pil` at your addon.xml
> 
> `<import addon="script.module.pil" version="1.1.7"/>`
> 
> the script.module.pil is basically pillow and maybe that will work then
it was on my todo list, looks like I should do that now.

thanks.
